"""create jobs table

Revision ID: 56dc77c3cd97
Revises: 3ddbd4d86113
Create Date: 2026-09-27 20:21:47.489059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56dc77c3cd97'
down_revision: Union[str, Sequence[str], None] = '3ddbd4d86113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'contract', 'temporary', 'internship', name='employment_type'), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('work_mode', sa.Enum('onsite', 'remote', 'hybrid', name='work_mode'), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('responsibilities', sa.String(), nullable=True),
    sa.Column('requirements', sa.String(), nullable=True),
    sa.Column('preferred_qualifications', sa.String(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('hiring_manager_id', sa.Uuid(), nullable=True),
    sa.Column('recruiter_id', sa.Uuid(), nullable=True),
    sa.Column('openings', sa.Integer(), nullable=False),
    sa.Column('target_hire_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'published', 'on_hold', 'closed', 'archived', name='job_status'), nullable=False),
    sa.Column('approval_status', sa.Enum('none', 'pending', 'approved', 'rejected', name='job_approval_status'), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('openings >= 1', name='ck_jobs_openings_positive'),
    sa.CheckConstraint('salary_max IS NULL OR salary_min IS NULL OR salary_min <= salary_max', name='ck_jobs_salary_range'),
    sa.ForeignKeyConstraint(['hiring_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_jobs_organization_slug')
    )
    op.create_index(op.f('ix_jobs_hiring_manager_id'), 'jobs', ['hiring_manager_id'], unique=False)
    op.create_index(op.f('ix_jobs_organization_id'), 'jobs', ['organization_id'], unique=False)
    op.create_index('ix_jobs_organization_status', 'jobs', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_jobs_recruiter_id'), 'jobs', ['recruiter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_recruiter_id'), table_name='jobs')
    op.drop_index('ix_jobs_organization_status', table_name='jobs')
    op.drop_index(op.f('ix_jobs_organization_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_hiring_manager_id'), table_name='jobs')
    op.drop_table('jobs')
    # Native PG enum types are not dropped with the table; remove them so
    # downgrade -> upgrade round-trips cleanly.
    sa.Enum(name='job_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='job_approval_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='employment_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='work_mode').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
